name: TestInputs
on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: "test"
        required: true
        default: "https://example.com"
      COMMON_TREE_URL:
        description: "test2"
        required: false
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Check Out
        uses: actions/checkout@v4
